import { readFileSync } from 'node:fs';

// The manifest is generated by vite-plugin-pwa from vite.config.ts, so there is
// no runtime module to import — reading the config as text is enough to catch a
// member being dropped, and these two are invisible to every other test: the
// share target is how Android hands us content, and the link-handling members
// are what keep the capture bookmarklet out of a browser tab.
const config = readFileSync('vite.config.ts', 'utf8');

describe('PWA manifest', () => {
  it('claims the whole origin as the app, and asks for its links', () => {
    expect(config).toContain("id: '/'");
    expect(config).toContain("scope: '/'");
    expect(config).toContain("handle_links: 'preferred'");
  });

  it('still declares the POST share target Android shares arrive through', () => {
    expect(config).toContain('share_target:');
    expect(config).toContain("action: '/share-target'");
    expect(config).toContain("method: 'POST'");
  });
});
