import { readFileSync } from 'node:fs';
import { CAPTURE_PROTOCOL } from '../../hooks/use-url-capture';

// The manifest is generated by vite-plugin-pwa from vite.config.ts, so there is
// no runtime module to import — reading the config as text is enough to catch a
// member being dropped, and these two are invisible to every other test: the
// share target is how Android hands us content, and the link-handling members
// are what keep the capture bookmarklet out of a browser tab.
const config = readFileSync('vite.config.ts', 'utf8');

describe('PWA manifest', () => {
  it('claims the whole origin as the app, and asks for its links', () => {
    expect(config).toContain("id: '/'");
    expect(config).toContain("scope: '/'");
    expect(config).toContain("handle_links: 'preferred'");
  });

  it('registers the capture protocol the desktop bookmarklet launches', () => {
    // Chrome will not capture window.open into an installed app, so this scheme
    // is the only reliable route from a bookmarklet to the app window.
    expect(config).toContain("url: '/?protocol=%s'");
    // Must match the scheme the app builds its links with, and must be
    // registrable: "web+" + ASCII lower alphas only (a digit in it is why the
    // first attempt never registered).
    const declared = /protocol: '([^']+)'/.exec(config)?.[1];
    expect(declared).toMatch(/^web\+[a-z]+$/);
    expect(`${declared}:`).toBe(CAPTURE_PROTOCOL);
  });

  it('still declares the POST share target Android shares arrive through', () => {
    expect(config).toContain('share_target:');
    expect(config).toContain("action: '/share-target'");
    expect(config).toContain("method: 'POST'");
  });
});
